### 获取8089用户信息
GET http://localhost:8089/?id=11
Content-Type: application/json


### 获取用户信息
POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.bruce.durpc.demo.api.UserService",
  "methodSign": "findById@2_int_java.lang.String",
  "args": [11,"bruce"]

}

### 获取订单信息
POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.bruce.durpc.demo.api.OrderService",
  "methodSign": "findById@1_int",
  "args": [20]

}

### toString
POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.bruce.durpc.demo.api.OrderService",
  "methodSign": "toString",
  "args": []

}