server:
  port: 8089

durpc:
  zk:
    server: localhost:2181
    root: durpc
  app:
    id: app1
    namespace: public
    env: dev
  consumer:
    faultLimit: 10
    grayRatio: 33
    halfOpenDelay: 60000
    halfOpenInitialDelay: 10000
    retries: 2
    timeout: 1000

duregistry:
  servers: http://localhost:8484


logging:
  level:
    root: error
    com.bruce.durpc: debug