server:
  port: 8089
durpc:
  zkServer: localhost:2181
  zkRoot: durpc

app:
  id: app1
  namespace: public
  env: dev
  retries: 2
  timeout: 1000
  grayRatio: 10  #10-100

logging:
  level:
    root: error
    com.bruce.durpc: debug