server:
  port: 8081
durpc:
  zk:
    server: localhost:2181
    root: durpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 300
duregistry:
  servers: http://localhost:8484

logging:
  level:
    root: error
    com.bruce: debug